# Generated by Django 5.2.7 on 2025-11-04 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='evento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='eventos.evento'),
            preserve_default=False,
        ),
    ]
